# Introduction to Numpy

In [157]:
import numpy as np

### Creating arrays

In [158]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [159]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [160]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [161]:
a = np.array([1, 2, 3, 5, 7, 12])

a

array([ 1,  2,  3,  5,  7, 12])

In [162]:
a[2]

np.int64(3)

In [163]:
a[2] = 10

In [164]:
a

array([ 1,  2, 10,  5,  7, 12])

In [165]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [166]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

.arange is similar to range

In [167]:
np.linspace(0, 1, 11) # 11 numbers from 0 to 1

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### Multi-dimensional arrays

In [168]:
np.zeros((5, 2))   # 5 rows, 2 columns

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [169]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [170]:
n[0, 1] # first row, second column

np.int64(2)

In [171]:
n[0, 1] = 20

n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [172]:
n[2]

array([7, 8, 9])

In [173]:
n[2] = [1, 1, 1]

n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [174]:
n[:, 1] # all rows, second column

array([20,  5,  1])

In [175]:
n[:, 2] = [0, 1, 2]

n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

### Randomly generated arrays

In [176]:
np.random.rand(5, 2) # 5 rows, 2 columns, random numbers from 0 to 1

array([[0.62113383, 0.52914209],
       [0.13457995, 0.51357812],
       [0.18443987, 0.78533515],
       [0.85397529, 0.49423684],
       [0.84656149, 0.07964548]])

In [177]:
np.random.seed(2)  # for reproducibility, same random numbers are generated each time
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [178]:
np.random.seed(2) 
100 * np.random.rand(5, 2) # scale to 0-100

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [179]:
np.random.seed(2) 
np.random.randint(low=0, high=100, size=(5, 2)) # random integers between 0 and 100, 5 rows, 2 columns

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]], dtype=int32)

In [180]:
np.random.seed(2) 
np.random.randn(5, 2) # normally distributed random numbers (mean 0, std 1)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

### Element-wise operations

In [181]:
a = np.arange(5)

a

array([0, 1, 2, 3, 4])

In [182]:
a + 1

array([1, 2, 3, 4, 5])

In [183]:
a * 2

array([0, 2, 4, 6, 8])

In [184]:
b = (10 + (a * 2)) ** 2 / 100

In [185]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [186]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [187]:
a / b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

### Comparison operations

In [188]:
a

array([0, 1, 2, 3, 4])

In [189]:
a >= 2

array([False, False,  True,  True,  True])

In [190]:
b 

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [191]:
a > b # element-wise comparison.. what elements in a are greater than corresponding elements in b

array([False, False,  True,  True,  True])

In [192]:
a[a > b] # elements in a that are greater than corresponding elements in b... it returns the actual values of a that satisfy the condition

array([2, 3, 4])

### Summarizing operations

In [193]:
a

array([0, 1, 2, 3, 4])

In [194]:
a.min()

np.int64(0)

In [195]:
a.max()

np.int64(4)

In [196]:
a.sum()

np.int64(10)

In [197]:
a.mean()

np.float64(2.0)

In [198]:
a.std()

np.float64(1.4142135623730951)

In [199]:
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

In [200]:
n.sum() # sum of all elements in the array n

np.int64(35)

In [201]:
n.mean() # mean of all elements in the array n

np.float64(3.888888888888889)

In [202]:
n.max()

np.int64(20)

In [203]:
n.max(axis=0) # max of each column

array([ 4, 20,  2])

In [204]:
n.max(axis=1) # max of each row

array([20,  5,  2])