# [Linear Algebra](https://www.youtube.com/watch?v=zZyKUeOR4Gg&list=PL3MmuxUbc_hIhxl5Ji8t4O6lPAOpHaCLR&index=10)

In [167]:
import numpy as np

### Vector operations

In [168]:
u = np.array([2, 4, 5, 6]) # vector u

u

array([2, 4, 5, 6])

In [169]:
v = np.array([1, 0, 0, 2]) # vector v

v

array([1, 0, 0, 2])

In [170]:
u + v

array([3, 4, 5, 8])

In [171]:
(u + v) / 2 * u

array([ 3. ,  8. , 12.5, 24. ])

In [172]:
u * v # element-wise multiplication... different from dot product in linear algebra

array([ 2,  0,  0, 12])

### Multiplication
- Vector-vector multiplication (dot product)
- Matrix-vector multiplication
- Matrix-matrix multiplication


if we wanna change a column vector to a row vector, we'll use `transpose`

##### _Vector-vector multiplication (dot product)_

In [173]:
u.shape[0]

4

In [174]:
v.shape

(4,)

In [175]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]       # Vectors must be the same length

    n = u.shape[0]

    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]     # or  # result += u[i] * v[i]

    return result

In [176]:
print(vector_vector_multiplication(u, v))

14.0


...in numpy, you can also do this instead of using the function

In [177]:
print(u.dot(v))

14


##### _Matrix-vector multiplication_

In [178]:
U = np.array(           # matrix U
    [[2, 4, 5, 6],
     [1, 2, 1, 2],
     [3, 1, 2, 1]]
)

U    

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [179]:
print(U)

[[2 4 5 6]
 [1 2 1 2]
 [3 1 2 1]]


In [180]:
U.shape

(3, 4)

In [181]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]      

    num_rows = U.shape[0]                        

    result = np.zeros(num_rows)  
                    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v) 

    return result

In [182]:
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

...using numpy

In [183]:
U.dot(v)

array([14,  5,  5])

##### _Matrix-matrix multiplication_

In [184]:
V = np.array(           # matrix V
    [[1, 1, 2],
     [0, 0.5, 1],
     [0, 2, 1],
     [2, 1, 0]
])

V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [185]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [186]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]      

    num_rows = U.shape[0]                        
    num_cols = V.shape[1]                        

    result = np.zeros((num_rows, num_cols))  
                    
    for i in range(num_rows):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi

    return result

In [187]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

...using numpy

In [188]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

### Identity Matrix (I)

e.g `U . I = U`
    or
    `I . U = U`


identity matrix (I) is like 1... such that anything multiplied by 1 returns that thing

e.g `1 . x = x` or `x . 1 = x`

In [189]:
I_mx = np.eye(10)  # identity matrix of size 10x10
print(I_mx)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [190]:
I = np.eye(3)  # identity matrix of size 3x3
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [191]:
print(V)

[[1.  1.  2. ]
 [0.  0.5 1. ]
 [0.  2.  1. ]
 [2.  1.  0. ]]


In [192]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

Identity Matrix is useful for understanding Matrix Inverse

### Matrix inverse

In [193]:
Vs = V[[0, 1, 2]]  # square matrix from V
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [194]:
Vs_inv = np.linalg.inv(Vs) # matrix inverse
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [195]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

...quite useful for Linear regression