##### Q1. Pandas version
What version of Pandas did you install?

In [310]:
import pandas as pd
pd.__version__

'2.3.2'

In [311]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

##### Q2. Records count

How many records are in the dataset?

In [312]:
df.shape[0]

9704

##### Q3. Fuel types
How many fuel types are presented in the dataset?

In [313]:
# df['fuel_type'].nunique()

    # # or

(df['fuel_type'].unique()).shape[0]

2

##### Q4. Missing values
How many columns in the dataset have missing values?

In [314]:
# df.info()

mss = df.isnull().sum()

cols_with_missing_values = mss[mss > 0].count()

print(cols_with_missing_values)

4


##### Q5. Max fuel efficiency
What's the maximum fuel efficiency of cars from Asia?



In [315]:
# print(df['origin'].unique())

print(df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max())

23.759122836520497


##### Q6. Median value of horsepower
- Find the median value of the horsepower column in the dataset.
- Next, calculate the most frequent value of the same horsepower column.
- Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
- Now, calculate the median value of horsepower once again.

Has it changed?

In [316]:
print(df['horsepower'].median(), '- median value of horsepower column')

149.0 - median value of horsepower column


In [317]:
print(df['horsepower'].mode()[0], '- most frequent value of horsepower column')

152.0 - most frequent value of horsepower column


In [318]:
print(df[df['horsepower'].isnull() == True]['horsepower'].shape[0], 'missing values in horsepower column')

708 missing values in horsepower column


In [319]:
mode = df['horsepower'].mode()[0]
mode

df['horsepower'] = df['horsepower'].fillna(mode)

print('The median has now changed to', df['horsepower'].median())

The median has now changed to 152.0


##### Q7. Sum of weights
- Select all the cars from Asia
- Select only columns `vehicle_weight` and `model_year`
- Select the first 7 values
- Get the underlying NumPy array. Let's call it `X`.
- Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
- Invert `XTX`.
- Create an array `y` with values `[1100, 1300, 800, 900, 1000, 1100, 1200]`.
- Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
- What's the sum of all the elements of the result?

In [320]:
# df[df['origin'] == 'Asia']
# df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']]
mini_data = df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']].head(7)

mini_data

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [321]:
import numpy as np

X = np.array(mini_data)

X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

transposing `X`

In [322]:
XTX = X.T

XTX

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

inverting `XTX`

In [323]:
XTX_inv = np.linalg.pinv(XTX)

XTX_inv

array([[-1.31202622e-04,  2.62636846e-04],
       [-8.63909858e-05,  1.96990690e-04],
       [ 3.72634923e-04, -4.73392228e-04],
       [-4.02726650e-04,  6.58944477e-04],
       [-1.62513724e-04,  3.08357831e-04],
       [-5.52342829e-05,  1.51636137e-04],
       [ 4.65094049e-04, -6.07979633e-04]])

In [324]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

Multiplying the inverse of `XTX` with the transpose of `X`, and then multiplying the result by `y`

In [325]:
w = XTX_inv.dot(X.T).dot(y)

# w = XTX_inv * X.T * y

w

array([1055.52241015, 1053.45860756, 1063.01887374, 1046.30962673,
       1054.76281975, 1056.31505812, 1071.56369951])

In [326]:
w.sum()

np.float64(7400.951095565675)